version: '3.7'
services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: ft-nginx
    ports:
      - 443:443
    volumes:
      - ./wordpress_data:/var/www/app
  mariadb:
    build: ./requirements/mariadb
    image: ft-mariadb
    environment:
      - MYSQL_GROOT_HOST=%
      - MYSQL_GROOT_PASSWORD=${MYSQL_GROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/php-fpm
    image: ft-php-fpm
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./wordpress_data:/var/www/app
    command: ['sh', '-c',
    ' if [ "$$(ls -A /var/www/app)" ]; then echo "wordpress already downloaded"; exec php-fpm7 ; fi;
    echo "Persistent volume empty, downloading wordpress...";
    wget -q -O - https://github.com/WordPress/WordPress/archive/5.6.tar.gz | tar -xz -C /var/www/app --strip-components=1;
    echo "Done.";
    exec php-fpm7;
    ']

## Bonus
  ftp:
    build: ./requirements/ftp
    image: ft-ftp
    environment:
      - USER=${MYSQL_USER}
      - PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "21:21"
      - "20:20"
      - "20000-20002:20000-20002"
    volumes:
      - ./wordpress_data:/ftps_data

  redis:
    build: ./requirements/ftp
    image: ft-redis
